### ISSUE TITLE
2023 data?

### ISSUE THREAD

**Issue by stevearama11** [fboerman/gie-py#5]
my code breaks when i set the end_date to a day in 2023?

`Traceback (most recent call last):
  File "C:\Users\steve\PycharmProjects\natgas\main.py", line 564, in <module>
    main()
  File "C:\Users\steve\PycharmProjects\natgas\main.py", line 517, in main
    new_data = get_ng_data()
  File "C:\Users\steve\PycharmProjects\natgas\main.py", line 36, in get_ng_data
    d[key] = client.query_gas_country(value, start_date, end_date,)
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\gie\gie.py", line 117, in query_gas_country
    return self._fix_dataframe(
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\gie\gie.py", line 99, in _fix_dataframe
    df = df.drop(columns=['status']).astype(float)
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\pandas\core\generic.py", line 6240, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\pandas\core\internals\managers.py", line 450, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\pandas\core\internals\managers.py", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\pandas\core\internals\blocks.py", line 526, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\pandas\core\dtypes\astype.py", line 299, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\pandas\core\dtypes\astype.py", line 230, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "C:\Users\steve\PycharmProjects\natgas\venv\lib\site-packages\pandas\core\dtypes\astype.py", line 170, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: '-'`

**Comment by stevearama11** [comment]
When i remove several more  empty cols, and do not put status back it, it works. 
I'm too stupid to understand the reason, so I'll just leave it to someone who knows what they're talking about.
thanks for your api.

def _fix_dataframe(self, data):
        df = pd.DataFrame(data)
        for c in ['name', 'code', 'url', 'info']:
            if c in df:
                df = df.drop(columns=c)
        df = df.loc[df['status'] != 'N']
        df['gasDayStart'] = pd.to_datetime(df['gasDayStart'])
        df = df.set_index('gasDayStart')
        # status is only str column, save it for now, convert whole dataframe to float, restore status
        status = df['status'].copy()
        #df = df.drop(columns=['status']).astype(float)
        df = df.drop(columns=['status', 'consumption', 'consumptionFull']).astype(float)
        #df['status'] = status
        return df
